/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiYoutubeAvatarRouteImport } from './routes/api/youtube/avatar'
import { Route as ApiYoutubeStreamRouteImport } from './routes/api/youtube/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeAvatarRoute = ApiYoutubeAvatarRouteImport.update({
  id: '/api/youtube/avatar',
  path: '/api/youtube/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeStreamRoute = ApiYoutubeStreamRouteImport.update({
  id: '/api/youtube/stream',
  path: '/api/youtube/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/youtube/avatar': typeof ApiYoutubeAvatarRoute
  '/api/youtube/stream': typeof ApiYoutubeStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/youtube/avatar': typeof ApiYoutubeAvatarRoute
  '/api/youtube/stream': typeof ApiYoutubeStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/youtube/avatar': typeof ApiYoutubeAvatarRoute
  '/api/youtube/stream': typeof ApiYoutubeStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/youtube/avatar' | '/api/youtube/stream'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/youtube/avatar' | '/api/youtube/stream'
  id: '__root__' | '/' | '/api/youtube/avatar' | '/api/youtube/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiYoutubeAvatarRoute: typeof ApiYoutubeAvatarRoute
  ApiYoutubeStreamRoute: typeof ApiYoutubeStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/avatar': {
      id: '/api/youtube/avatar'
      path: '/api/youtube/avatar'
      fullPath: '/api/youtube/avatar'
      preLoaderRoute: typeof ApiYoutubeAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/stream': {
      id: '/api/youtube/stream'
      path: '/api/youtube/stream'
      fullPath: '/api/youtube/stream'
      preLoaderRoute: typeof ApiYoutubeStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiYoutubeAvatarRoute: ApiYoutubeAvatarRoute,
  ApiYoutubeStreamRoute: ApiYoutubeStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
